---

- name: Force Node online
  hosts: bigip
  connection: local

  tasks:
     - name: Force node online
       bigip_node:
         state: enabled
         name: QA01-BO01
         provider:
           server: “{{ f5_hostname }}”
           user: “{{ f5_username }}”
           password: “{{ f5_password }}”
           validate_certs: "false"

---


#- name: (Project Name)
#  hosts: (Hostname as ansible hosts file)
#  connection: local
#
#  tasks:
#     - name: #Task Name)
#       bigip_node:
#         state: (Node State) #present #absent #enabled #disabled #offline
#         name: #NodeName)
#         provider:
#           server: #"F5-IP" #X.X.X.X
#           user: #"username"
#           password: #"password"
#           validate_certs: #"ssh-key?" #false #yes #no    
