---
- hosts: nagios
  connection: local
  tasks:
    - name: Schedule an hour of HOST downtime
      delegate_to: ams-nagios01.frxfarm.local
      community.general.nagios:
        action: delete_downtime
        service: all
        host: 'InfoBIP'
        comment: 'Platform version'